services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    build: ./get_current_usd/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - redis
    